config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  #get  "/articles", to: "articles#index"
  #get "/articles/:id", to: "articles#show"
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles=Article.all
    end
    def show
        @article = Article.find(params[:id])
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(title: "...", body: "...")
        if @article.save
          redirect_to @article
        else
          render :new, status: :unprocessable_entity
        end
    end

    private
    def article_params
      params.require(:article).permit(:title, :body)
    end    
end 

app/views/articles/form.html.erb
<%= form_with model: article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/articles/index.html.erb
<h1> Hello</h1>
<p> welcome to ruby on ruby on fffdfrails</p>
<ul>
<% @articles.each do |article| %>
    <li>
    <a href "<%= article_path(article) %>">

    <%= article.title %>
    </a>
    </li>
    <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%
    @article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %> </div>
    <% end %>

  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <%
    @article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %> </div>
    <% end %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>